repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.4.0
      hooks:
          - id: check-json
          - id: pretty-format-json
            args: ["--autofix", "--indent=4"]
          - id: no-commit-to-branch
            args:
                [
                    "--branch",
                    "main",
                    "--branch",
                    "staging",
                    "--branch",
                    "production",
                ]

    - repo: https://github.com/golangci/golangci-lint
      rev: v1.51.2
      hooks:
          - id: golangci-lint

    - repo: https://github.com/Bahjat/pre-commit-golang
      rev: v1.0.3
      hooks:
          - id: go-unit-tests
